#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DisasterDetector.Resource", IsApplication=true)]

namespace DisasterDetector
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.Id.agentWebView = global::DisasterDetector.Resource.Id.agentWebView;
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.Layout.WebAuthenticationBroker = global::DisasterDetector.Resource.Layout.WebAuthenticationBroker;
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.String.ApplicationName = global::DisasterDetector.Resource.String.ApplicationName;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010005
			public const int max = 2130771973;
			
			// aapt resource value: 0x7f010000
			public const int ringColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int ringProgressColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int ringWidth = 2130771970;
			
			// aapt resource value: 0x7f010007
			public const int style = 2130771975;
			
			// aapt resource value: 0x7f010003
			public const int textColor = 2130771971;
			
			// aapt resource value: 0x7f010006
			public const int textIsShow = 2130771974;
			
			// aapt resource value: 0x7f010004
			public const int textSize = 2130771972;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int colorAccent = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int colorPrimary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int colorPrimaryDark = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int logo1 = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000b
			public const int EditText1 = 2131099659;
			
			// aapt resource value: 0x7f060000
			public const int FILL = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int Name = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int PhoneNumber = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int STROKE = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int Text = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int Text1 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int Text2 = 2131099653;
			
			// aapt resource value: 0x7f06000e
			public const int agentWebView = 2131099662;
			
			// aapt resource value: 0x7f060009
			public const int latitude = 2131099657;
			
			// aapt resource value: 0x7f060002
			public const int listView1 = 2131099650;
			
			// aapt resource value: 0x7f06000a
			public const int longitude = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int phone = 2131099655;
			
			// aapt resource value: 0x7f06000c
			public const int progress_bar_1 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int progress_bar_2 = 2131099661;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int listBlueTooth = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int startpage = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int WebAuthenticationBroker = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RingProgressBar = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: 5
			public const int RingProgressBar_max = 5;
			
			// aapt resource value: 0
			public const int RingProgressBar_ringColor = 0;
			
			// aapt resource value: 1
			public const int RingProgressBar_ringProgressColor = 1;
			
			// aapt resource value: 2
			public const int RingProgressBar_ringWidth = 2;
			
			// aapt resource value: 7
			public const int RingProgressBar_style = 7;
			
			// aapt resource value: 3
			public const int RingProgressBar_textColor = 3;
			
			// aapt resource value: 6
			public const int RingProgressBar_textIsShow = 6;
			
			// aapt resource value: 4
			public const int RingProgressBar_textSize = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
